syntax = "proto3";

package program;

option go_package = "program/program";

service ChittyChat {
  //User connects to chatservice
  rpc SendMessageToProgram(SendMessage) returns (MessageSent);
  //Posts a chatmessage
  rpc ConnectClient(ClientName) returns (stream MessagePublished);
}

message SendMessage{
  string user = 1;
  string message = 2;
  int64 timestamp = 3;
}

message MessagePublished {
  string message = 1;
  int64 timestamp = 2;
}

message ClientName{
  string user = 1;
}

message MessageSent{
  string server = 1;
  int64 timestamp = 2;
}
