// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package program

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChittyChatClient is the client API for ChittyChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChittyChatClient interface {
	//User connects to chatservice
	SendMessageToProgram(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*MessageSent, error)
	//Posts a chatmessage
	ConnectClient(ctx context.Context, in *ClientName, opts ...grpc.CallOption) (ChittyChat_ConnectClientClient, error)
}

type chittyChatClient struct {
	cc grpc.ClientConnInterface
}

func NewChittyChatClient(cc grpc.ClientConnInterface) ChittyChatClient {
	return &chittyChatClient{cc}
}

func (c *chittyChatClient) SendMessageToProgram(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*MessageSent, error) {
	out := new(MessageSent)
	err := c.cc.Invoke(ctx, "/program.ChittyChat/SendMessageToProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chittyChatClient) ConnectClient(ctx context.Context, in *ClientName, opts ...grpc.CallOption) (ChittyChat_ConnectClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChat_ServiceDesc.Streams[0], "/program.ChittyChat/ConnectClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatConnectClientClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChittyChat_ConnectClientClient interface {
	Recv() (*MessagePublished, error)
	grpc.ClientStream
}

type chittyChatConnectClientClient struct {
	grpc.ClientStream
}

func (x *chittyChatConnectClientClient) Recv() (*MessagePublished, error) {
	m := new(MessagePublished)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatServer is the server API for ChittyChat service.
// All implementations must embed UnimplementedChittyChatServer
// for forward compatibility
type ChittyChatServer interface {
	//User connects to chatservice
	SendMessageToProgram(context.Context, *SendMessage) (*MessageSent, error)
	//Posts a chatmessage
	ConnectClient(*ClientName, ChittyChat_ConnectClientServer) error
	mustEmbedUnimplementedChittyChatServer()
}

// UnimplementedChittyChatServer must be embedded to have forward compatible implementations.
type UnimplementedChittyChatServer struct {
}

func (UnimplementedChittyChatServer) SendMessageToProgram(context.Context, *SendMessage) (*MessageSent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToProgram not implemented")
}
func (UnimplementedChittyChatServer) ConnectClient(*ClientName, ChittyChat_ConnectClientServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectClient not implemented")
}
func (UnimplementedChittyChatServer) mustEmbedUnimplementedChittyChatServer() {}

// UnsafeChittyChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittyChatServer will
// result in compilation errors.
type UnsafeChittyChatServer interface {
	mustEmbedUnimplementedChittyChatServer()
}

func RegisterChittyChatServer(s grpc.ServiceRegistrar, srv ChittyChatServer) {
	s.RegisterService(&ChittyChat_ServiceDesc, srv)
}

func _ChittyChat_SendMessageToProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChittyChatServer).SendMessageToProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/program.ChittyChat/SendMessageToProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChittyChatServer).SendMessageToProgram(ctx, req.(*SendMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChittyChat_ConnectClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientName)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChittyChatServer).ConnectClient(m, &chittyChatConnectClientServer{stream})
}

type ChittyChat_ConnectClientServer interface {
	Send(*MessagePublished) error
	grpc.ServerStream
}

type chittyChatConnectClientServer struct {
	grpc.ServerStream
}

func (x *chittyChatConnectClientServer) Send(m *MessagePublished) error {
	return x.ServerStream.SendMsg(m)
}

// ChittyChat_ServiceDesc is the grpc.ServiceDesc for ChittyChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChittyChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "program.ChittyChat",
	HandlerType: (*ChittyChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageToProgram",
			Handler:    _ChittyChat_SendMessageToProgram_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectClient",
			Handler:       _ChittyChat_ConnectClient_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "program/program.proto",
}
